### ISSUE TITLE
Doesn't work out of the box

### ISSUE THREAD

**Issue by marhoily** [archi-Doc/Tinyhand#115]
1. In VS2019 create a new .net 5 console app 
2. Copy-paste the sample code from the getting started section 
(I uploaded the code [here](https://github.com/marhoily/TinyhandBug))
3. Run
4. Exception:
Tinyhand.TinyhandException
  HResult=0x80131500
  Message=Failed to serialize TinyhandBug.MyClass value.
  Source=Tinyhand
  StackTrace:
   at Tinyhand.TinyhandSerializer.Serialize[T](T value, TinyhandSerializerOptions options, CancellationToken cancellationToken)
   at TinyhandBug.Program.Main(String[] args) in C:\Users\marhoily\source\repos\TinyhandBug\TinyhandBug\Program.cs:line 14

  This exception was originally thrown at this call stack:
    [External Code]

Inner Exception 1:
FormatterNotRegisteredException: TinyhandBug.MyClass is not registered in resolver: Tinyhand.Resolvers.StandardResolver

---------
Observations:
1. No partial class seems to be generated
2. When I enable `<TreatWarningsAsErrors>true</TreatWarningsAsErrors>` I get the following error
An instance of analyzer Tinyhand.Generator.TinyhandGenerator cannot be created from C:\Users\marhoily\.nuget\packages\tinyhand\0.24.1\analyzers\dotnet\cs\TinyhandGenerator.dll : Could not load file or assembly 'Microsoft.CodeAnalysis, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified..

**Comment by archi-Doc** [comment]
@marhoily 
#116 

Thanks for the detailed report.
I could not reproduce this issue with my VS 2022 though.

I suspect that the source generator not working at all due to nuget assembly inconsistency (Microsoft.CodeAnalysis?).
It's a bug in Roslyn and Source Generator/Analyzer.

I have reverted to Microsoft.CodeAnalysis 3.11.0.
Hope it works in your environment.
