### ISSUE TITLE
NativeAOT: This operation is only valid on generic types

### ISSUE THREAD

**Issue by clarvalon** [archi-Doc/Tinyhand#95]
Is being compatible with ahead-of-time compilation a goal of Tinyhand?  The following works fine in Debug & Release:

```csharp
using Tinyhand;
using ns;
var engineTinyHandOptions = Tinyhand.TinyhandSerializerOptions.Standard; 

// Create simple test object, serialize to file
var obj = new Test() { Str = "TestString", i = 1 }; 
var bytes = Tinyhand.TinyhandSerializer.Serialize<Test>(obj, engineTinyHandOptions);
File.WriteAllBytes("out.th", bytes);

// Deserialise from file
FileStream stream = new FileStream("out.th", FileMode.Open);
var returnObject = Tinyhand.TinyhandSerializer.Deserialize<Test>(stream, engineTinyHandOptions);
Console.WriteLine(returnObject.Str);
stream.Close();

namespace ns
{
    [Tinyhand.TinyhandObject(ImplicitKeyAsName = true)]
    public partial class Test
    {
        public string Str;
        public int i;
    }
}
```

However if I publish as a self-contained executable using [NativeAOT](https://github.com/dotnet/runtimelab/tree/feature/NativeAOT) I get the following error at runtime:

```
Unhandled Exception: Tinyhand.TinyhandException: Failed to serialize ns.Test value.
 ---> System.TypeInitializationException: A type initializer threw an exception. To determine which type, inspect the InnerException's StackTrace property.
 ---> System.InvalidOperationException: This operation is only valid on generic types.
   at System.Reflection.Runtime.TypeInfos.RuntimeTypeInfo.GetGenericTypeDefinition() + 0x33
   at System.Reflection.Runtime.TypeInfos.NativeFormat.NativeFormatRuntimeNamedTypeInfo.GetGenericTypeDefinition() + 0xe9
   at Tinyhand.Resolvers.GeneratedResolver.TryGetFormatter[T]() + 0x57
   at Tinyhand.Resolvers.StandardResolver.FormatterCache`1..cctor() + 0xb4
   at System.Runtime.CompilerServices.ClassConstructorRunner.EnsureClassConstructorRun(StaticClassConstructionContext*) + 0xd6
   --- End of inner exception stack trace ---
   at System.Runtime.CompilerServices.ClassConstructorRunner.EnsureClassConstructorRun(StaticClassConstructionContext*) + 0x16f
   at System.Runtime.CompilerServices.ClassConstructorRunner.CheckStaticClassConstructionReturnGCStaticBase(StaticClassConstructionContext*, Object) + 0xd
   at Tinyhand.Resolvers.StandardResolver.TryGetFormatter[T]() + 0x11
   at Tinyhand.ResolverExtensions.GetFormatter[T](IFormatterResolver) + 0x39
   at Tinyhand.TinyhandSerializer.Serialize[T](T, TinyhandSerializerOptions, CancellationToken) + 0x164
   --- End of inner exception stack trace ---
   at Tinyhand.TinyhandSerializer.Serialize[T](T, TinyhandSerializerOptions, CancellationToken) + 0x21e
   at <Program>$.<Main>$(String[]) + 0x74
   at ConsoleApp1!<BaseAddress>+0x3427ba
```

Changing the resolver (e.g. to only use GeneratedResolver, or a CompositeResolver) doesn't appear to help.  This is using the  latest version of Tinyhand from nuget (0.20.1).  Perhaps we are missing a ```.IsGenericType``` check somewhere?

Supporting AOT platforms (e.g. iOS, consoles) is a goal of the [MessagePack-CSharp](https://github.com/neuecc/MessagePack-CSharp#aot-code-generation-support-for-unityxamarin) project, albeit using their custom mpc.exe solution for generating code, rather than using a source generator.

**Comment by archi-Doc** [comment]
@clarvalon 
Thanks for the bug report
I fixed the issue.

- I added `.IsGenericType` check in `GeneratedResolver.TryGetFormatter()`as you mentioned.
- `TinyhandModule.Initialize()` is required in your code.

```csharp
// Add this code before Serialize()
TinyhandModule_YourAssemblyName.Initialize(); // Adding assembly name is required to avoid name conflict in multiple assemblies.
```

By default, Tinyhand loads generated formatters using `ModuleInitializerAttribute`.
But it seems `ModuleInitializerAttribute` doesn't work when using NativeAOT + publishing as a self-contained executable.

It may be NativeAOT's problem.
The current solution is to call the Initializer method manually.

Supporting AOT platforms is the main reason I chose a source generator rather than dynamic code generation.

**Comment by archi-Doc** [comment]
#96 
#97

**Comment by clarvalon** [comment]
Thank you for the quick turnaround, and your excellent work on this project!

I can confirm the fix and call to ```Initialize()``` works.  I've now gotten my engine working with NativeAOT & TinyHand for state serialization, and performance is absurdly fast 😄 

![image](https://user-images.githubusercontent.com/523011/132133045-43bf92a0-0222-457b-8a54-ab92032932b3.png)

**Comment by archi-Doc** [comment]
Glad it worked out.
Let me know if you have any questions.
