### ISSUE TITLE
Assembly names with non-alpha characters causing invalid classname in generated code

### ISSUE THREAD

**Issue by clarvalon** [archi-Doc/Tinyhand#99]
Quick one - an assembly name with a non-alpha character e.g.:

```<AssemblyName>My.Project</AssemblyName>```

Will result in an error, as the generated code contains an invalid class name:

```public static class TinyhandModule_My.Project```

It's easy enough to work around, but I'm guessing these characters should be substituted or stripped out of the generated classname.

**Comment by archi-Doc** [comment]
Thanks a lot.

#100 
This is a quick fix.
It replace invalid characters with '_'
Obviously project A_B and A.B will cause name conflict, but it's not good naming convention.

**Comment by clarvalon** [comment]
Perfect, thank you!
